### ISSUE TITLE
Typechecker cruft tracking issue

### ISSUE THREAD

**Issue by SebastianMestre** [SebastianMestre/Jasper#326]
As discussed on #324, there are a lot of legacy issues in the typechecker that make it buggy and more complex than it needs to be. Here are some ideas that popped up after reading through the most important functions

- [x] remove typefunc unification variables (#324)
- [ ] expose a better typevar constraint API, replacing the `new_dummy_*` family
- [ ] check typevar constraints -- right now `satisfies()` just returns true
- [ ] expose better, shorter-named APIs for creating types (#324, #325)
- [x] use `VarId` instead of `MonoId` in `PolyData` and `gather_free_vars` (#325)
- [ ] simplify ct_eval ... somehow (#324)
